# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: colearn_dev
  host: localhost
  pool: 5
  username: colearn
  password: colearn

test:
  adapter: postgresql
  encoding: unicode
  database: colearn_test
  pool: 5
  username: colearn
  password: colearn

